services:
  
  myapp:
    image: marcellodesales/my-python-service
    platform: linux/x86_64
    build:
      context: .
      target: service
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data

    restart: unless-stopped


