####
#### Starts a single service with a DB in memory
####
#### docker compose up --build
####
services:
  
  myapp:
    image: marcellodesales/my-python-service

    platform: linux/x86_64
    build:
      context: .
      target: service

    environment:
      LOG_LEVEL: INFO

    ports:
      - "8080:8081"

    restart: unless-stopped
